### PR TITLE
feat: implement batch entity delete endpoint #63

### PR DESCRIPTION
**Pull request by philippestoltz**

### CODE REVIEW

**Comment by philippestoltz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bobeal** [comment]
Can you rebase it on the "EOL PR" to remove the LF/CRLF noise from this PR?

(Or we wait for the EOL PR to be merged before reviewing this PR)

**Comment by philippestoltz** [comment]
> Can you rebase it on the "EOL PR" to remove the LF/CRLF noise from this PR?
> 
> (Or we wait for the EOL PR to be merged before reviewing this PR)

Done

**Comment by philippestoltz** [comment]
check other PR

**Pull request closed without merging**
